name: pages build and deployment
permissions:
  contents: read
  pages: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy to GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: .
